### ISSUE TITLE
Missing peer dependency

### ISSUE THREAD

**Issue by ebrpol** [mrseanryan/tslint-folders-diagrams#24]
Yarn 2 yields the following error message:

➤ YN0002: │ tslint-folders-diagrams@npm:3.1.1 doesn't provide tslint@* requested by tslint-folders@npm:4.0.1
➤ YN0002: │ tslint-folders-diagrams@npm:3.1.1 doesn't provide typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev || >=3.0.0-dev || >=3.1.0-dev || >=3.2.0-dev || >=3.3.0-dev requested by tslint-folders@npm:4.0.1

See https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency for description of the problem.

Could you add tslint and typescript as peer-dependencies?

**Comment by mrseanryan** [comment]
@ebrpol  fixed in 3.1.2

Thank you for reporting it!
